## BCIS 5110 - Assignment 7
Q1: 3 points each sub-question. Q2: 9 points

### 1. Manipulate arrays
The purpose of the assignment is to work with n-dimensional arrays.

In [1]:
import numpy as np

1.1 Create a 5X4 array with random integer between 1 and 100. The required arguments of the creation function to do this is np.random.randint(low, high, size). As usual, low is inclusive and high is exclusive.

In [2]:
mat = np.random.randint(1, 100, (5, 4))
mat

array([[20, 75, 14, 94],
       [43, 41, 95, 83],
       [53, 16, 37, 34],
       [ 1,  7, 46, 28],
       [41, 14, 23, 53]])

1.2 Change the element of second row/third column to 0

In [3]:
mat[1, 2] = 0
mat

array([[20, 75, 14, 94],
       [43, 41,  0, 83],
       [53, 16, 37, 34],
       [ 1,  7, 46, 28],
       [41, 14, 23, 53]])

1.3 Create a slice of two rows and three columns (row 2 and 3, column 2-4). Your way of creation should guarantee that changing the slice will not change the original array. Change the element at row 2 and column 2 in the slice to 100. Print the slice before and after change.

In [4]:
mat_slice = mat[1:3, 1:4]
mat_slice
mat_slice[1, 1] = 100
mat_slice

array([[ 41,   0,  83],
       [ 16, 100,  34]])

1.4 Create a two-dimensional array with 5 integers in one row. You can create it your own way. <br>
Can this array and the one created in 1.1 be added together?

In [5]:
mat2 = np.array([1, 2, 3, 4, 5])
mat2
mat + mat2 #No it cant be added togather because they are in different shape

ValueError: operands could not be broadcast together with shapes (5,4) (5,) 

1.5 Following 1.4, how can we make the two arrays add together?

In [6]:
add_mat = mat + mat2.reshape(5, 1) # we can use reshape() to add the array
add_mat

array([[ 21,  76,  15,  95],
       [ 45,  43,   2,  85],
       [ 56,  19, 103,  37],
       [  5,  11,  50,  32],
       [ 46,  19,  28,  58]])

1.6 Multiply the elements (in the 5X4 array created in 1.1) that are divisable by 3 with 2.

In [8]:
mul_mat = np.where(mat % 3 == 0, mat * 2, mat)
mul_mat

array([[ 20, 150,  14,  94],
       [ 43,  41,   0,  83],
       [ 53,  16, 100,  34],
       [  1,   7,  46,  28],
       [ 41,  14,  23,  53]])

1.7 Calculate the mean and the standard deviation of each column using aggregation functions of the array from 1.1. Use the mean and std to get the standardized value of each element using the formula: (x - mean)/std, where x is the element. Tips: Which axis should we use?

In [12]:
mean_mat = np.mean(mat, axis=0) # axis = 0 represents the operation along the rows, meaning that for each column, the mean and standard deviation will be calculated by considering all the elements within that particular column.
mean_mat

array([31.6, 30.6, 36.6, 58.4])

In [10]:
std_mat = np.std(mat, axis=0)
std_mat

array([18.69331431, 25.00079999, 35.05196143, 26.15798157])

In [7]:
stand_mat = (mat - mean_mat) / std_mat
stand_mat

array([[-0.62054271,  1.77594317, -0.64475707,  1.36096128],
       [ 0.6098437 ,  0.41598669, -1.04416411,  0.94043953],
       [ 1.14479432, -0.58398131,  1.80874329, -0.93279368],
       [-1.63694888, -0.94396979,  0.2681733 , -1.16216918],
       [ 0.50285358, -0.66397875, -0.38799541, -0.20643795]])

### 2. Write a Python function to implement a simple encryption technique.<br>

In this encryption, each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet. For example, with a left shift of 3, D would be replaced by A, E would become B, and so on. <br>
Your function takes two arguments, the original words and the number of steps to shift (Left shift negative and right shift positive).

Sample input: 'apple', -3<br>
Output with left shift of 3: 'xmmib'

You may define the alphabet as a list. Each letter has its position.
Left shift of 3 means index - 3 and right shift means index + 3.

Tip: How can you make sure the index is between 0-25? Negative index can also be used.


In [15]:
def encrypt(word, shift):
  alphabet = 'abcdefghijklmnopqrstuvwxyz'
  encrypted_word = ''
  for letter in word:
    if letter in alphabet:
      letter_index = alphabet.index(letter)
      new_index = (letter_index + shift) % 26
      encrypted_word += alphabet[new_index]
    else:
      encrypted_word += letter
  return encrypted_word

# Example usage
word = 'apple'
shift = -3
encrypted_word = encrypt(word, shift)
print(encrypted_word)  # Output: xmmib

xmmib
